apiVersion: 1

datasources:
  - name: CloudWatch
    type: cloudwatch
    jsonData:
      authType: credentials
      defaultRegion: ${GF_AWS_default_REGION}
    isDefault: true
    editable: true

  - name: Elasticsearch-Logs-Dev
    type: elasticsearch
    access: proxy
    editable: true
    database: "filebeat-*"
    basicAuth: true
    basicAuthUser: ${ES_LOGS_REMOTE_USER}
    url: ${ES_LOGS_REMOTE_HOST}
    secureJsonData:
      basicAuthPassword:
    jsonData:
      timeField: "@timestamp"
      esVersion: 70
      logMessageField: message
      logLevelField: fields.level

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      timeInterval: 10s
      queryTimeout: 30s
      httpMethod: POST

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
