# # config file version
# apiVersion: 1

notifiers:
  - name: default-slack
    type: slack
    is_default: true
    uid: notifier1
    frequency: 1h
    disable_resolve_message: false
    settings:
      recipient: ${NOTIFICATION_SLACK_RECIPIENT}
      token: ${NOTIFICATION_SLACK_TOKEN}
      uploadImage: true
      url: ${NOTIFICATION_SLACK_URL}

  - name: default-email
    type: email
    org_id: 1
    uid: notifier2
    is_default: false
    settings:
      addresses: email@gmail.com
#################################
############ example ############
#################################
# notifiers:
#   - name: default-slack-temp
#     type: slack
#     org_name: Main Org.
#     is_default: true
#     uid: notifier1
#     settings:
#       recipient: "XXX"
#       token: "xoxb"
#       uploadImage: true
#       url: https://slack.com
#   - name: default-email
#     type: email
#     org_id: 1
#     uid: notifier2
#     is_default: false
#     settings:
#       addresses: example11111@example.com
# delete_notifiers:
#   - name: default-slack-temp
#     org_name: Main Org.
#     uid: notifier1
